comments/urls.py
from django.urls import path
from comments import views

app_name='comments'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('', views.index, name='index'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),

]

elements/urls.py
from django.urls import path
from elements import views

urlpatterns = [
    path('element/', views.ElementsView, name='home'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('comments.urls')),
    #path('', include('elements.urls')),
    
]

comments/models.py
from django.db import models
from elements.models import Element

# Create your models here.

class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    element = models.ForeignKey(Element, on_delete=models.CASCADE, null=True, blank=True)
    
    def formatted_datePost(self):
        return self.date_posted.strftime('%Y-%m-%d %I:%M %p')
    
    def __str__(self):
        return 'Comment #{}'.format(self.id)
    
    
    

elements/models.py
from django.db import models
from django.contrib import admin
from django.core.exceptions import ValidationError

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=250)
    slug  = models.SlugField(max_length=250)
    
    def __str__(self):
        return self.title


class Type(models.Model):
    title = models.CharField(max_length=250)
    slug  = models.SlugField(max_length=250)
    
    def __str__(self):
        return self.title

class Element(models.Model):
    title = models.CharField(max_length=250)
    slug  = models.SlugField(max_length=250,blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default= 0.00)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    
    def adminCreateDate(self):
        return self.create.strftime('%Y-%m-%d %I:%M %p')
    adminCreateDate.short_description = 'Fecha de Creación'
    
    def adminUpdateDate(self):
        return self.update.strftime('%Y-%m-%d %I:%M %p')
    adminUpdateDate.short_description = 'Última Actualización'
    
    @admin.display(boolean=True)
    def cheap(self):
        return 0 <= self.price < 9.99
    
    def _str_(self):
        return self.title
    
    def clean(self):
        if self.price < 0:
            raise ValidationError("Precio no puede ser negativo.")

comments/forms.py
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

comments/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic.base import TemplateView
from datetime import datetime
#from django.http import Http404

from comments.forms import CommentForm
from .models import Comment

from django.core.paginator import Paginator
# Create your views here.

# def add(request):
    
#     if request.method == 'POST':
#         if request.POST.get('text') != '':
#             print('Adding')
#             comment = Comment()
#             comment.text = request.POST.get('text')
#             comment.save()
            
#         else: 
#             print('No data')
    
#     data = {'year': datetime.now().year,
#             'month': datetime.now().month,
#             'day': datetime.now().day,
#             'hour': datetime.now().hour,
#             'minute': datetime.now().minute,
#             'second': datetime.now().second,
#             'autor' : 'Ernesto Marquez'}
#     return render(request, 'comments/add.html', {'data': data})

def add(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        comment = form.save()
        return redirect('comments:index')
    else: 
        form = CommentForm()  
    return render(request, 'comments/add.html',{'form': form})

def index(request):
    comment = Comment.objects.all()
    paginator = Paginator(comment,2) 
    page_number = request.GET.get('page')
    comments_page = paginator.get_page(page_number) 
    return render(request, 'comments/index.html', {'comments': comments_page})


def update(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    # try:
    #     comment = Comment.objects.get(pk=pk)
    # except Comment.DoesNotExist :
    #     raise Http404
        
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        
        if form.is_valid():
            form.save()
            return redirect('comments:index')
    else:      
        form = CommentForm(instance=comment)
    return render(request, 'comments/add.html', {'form': form})

def delete(request, pk):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('comments:index')
        #return render(request, 'comments/index.html', {'comments': comment})

elements/views.py
from django.shortcuts import render

# Create your views here.

def ElementsView(request):
    pass

comments/templates/comments/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add</title>
</head>
<body>
    <h1>Pagina para agregar</h1>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo beatae adipisci dolorum officiis modi tempore labore aperiam obcaecati rem. Quo ab dolore itaque maiores numquam adipisci sed dolores, omnis veritatis.</p>
    <p>
    {{ data.autor }}
    </p>
    <p>El Año: {{data.year}}, el mes: {{data.month}}, el dia: {{data.day}}</p>

    {% comment %} <form action="{% url 'comments:add' %}" method="POST"> 
        <label for="">Text:</label>
        <textarea required name="text"></textarea>
        {% csrf_token %}
        <button type="submit">Send</button>
    </form> {% endcomment %}

    
    <form action="" method="POST"> 
        {{ form.text }}
        {% csrf_token %}
        <button type="submit">Send</button>
    </form>

</body>
</html>

comments/templates/comments/home.html
<!doctype html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            <!-- place navbar here -->
        </header>
        <main>
            <h1>{{messages}}</h1>
            <p>{{ fecha }}</p>
        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

comments/templates/comments/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de Comentarios</title>
</head>
<body>
    <h1>Lista de Comentarios</h1>
    
    {% if comments %}
    <ul>
        {% for comment in comments %}
        <li>{{ comment.date_posted }} - {{ comment.text }} -- <a href="{% url 'comments:update' comment.id %}">Editar</a> -- 
        <form action="{% url 'comments:delete' comment.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Borrar">
        </form>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <h2>Agregar Comentario</h2>
    <a href="{% url 'comments:add' %}">Crear Comentarios</a>

    <nav>
        <ul class="pagination justify-content-center">
            {% if comments.has_previous %}
                <li class="page-item">
                <a class="page-link" href="?page={{ comments.previous_page_number}}">Prev</a>
                </li> 
            {% endif %}
            <li class="page-item"> 
                {% for i in comments.paginator.page_range %}
                    {% if i == comments.number %}
                    <a href="?page={{i}}" class="page-link active">{{i}}</a>
                    {% else %}
                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                    {% endif %}
                {% endfor %}     
            </li>
            {% if comments.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{ comments.next_page_number}}">Next</a>
            </li> 
            {% endif %}
        </ul>
    </nav>
</body>
</html>